services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 1gb
    working_dir: /app
    restart: always
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    ports:
      - "8000:8000"
